### ISSUE TITLE
Widget text is too small

### ISSUE THREAD

**Issue by AvoCada** [isaacy2012/Sunset#10]
Compare it to the size of the app names. Using default system font size.

This is especially not good for older users others with poorer vision.
![Screenshot_20210227-203438_One UI Home](https://user-images.githubusercontent.com/23665199/109380866-068f8600-793c-11eb-9667-fcb195bb0e7b.jpg)

**Comment by isaacy2012** [comment]
Fixed as of `fb3a486`
