### ISSUE TITLE
Accidentally tapping the "+" button instead of "Okay" when creating a new task

### ISSUE THREAD

**Issue by AvoCada** [isaacy2012/Sunset#11]
When testing the app, I keep pressing the "+" instead of the "Okay" button when creating a new task, because the "+" is where a submit button is expected to be.

Also, the the Cancel and Okay buttons are quite hard to reach, especially on larger phones. Using Samsung Galaxy A8 Star.

![Screenshot_20210227-203220_Sunrise](https://user-images.githubusercontent.com/23665199/109381031-bbc23e00-793c-11eb-8b2b-ad0d0ce46e59.jpg)

**Comment by isaacy2012** [comment]
Fixed as of `fb3a486`
