### ISSUE TITLE
Add a "Completed Tasks" counter

### ISSUE THREAD

**Issue by AvoCada** [isaacy2012/Sunset#15]
In addition, perhaps highlight tasks in the archive that the user has completed that day.

**Comment by isaacy2012** [comment]
What would the completed tasks counter be for? If it was purely for motivation then we can add this when we add the Streak page (when the user clicks the streak button). 

As for the highlighting tasks, I have changed the text (where it says "Repeated x times before") to display "Task completed today" if the task was set AND completed today. This is to prevent a user mistakenly replaying a task they already did today.

**Comment by AvoCada** [comment]
I was thinking that it could remins the user that they have actually completed tasks today. But actually, showing what tasks they completed that day via the archive will probably do the job.
